FROM --platform=linux/x86_64 tiangolo/uvicorn-gunicorn-fastapi:python3.11
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

ENV APP_ROOT=/code

WORKDIR ${APP_ROOT}
COPY application/ ${APP_ROOT}/

RUN pip install --upgrade pip && pip install poetry
RUN poetry install --without dev

COPY ./containers/fastapi/entrypoint.prd.sh /usr/local/bin/entrypoint.prd.sh
RUN chmod +x /usr/local/bin/entrypoint.prd.sh
ENTRYPOINT ["entrypoint.prd.sh"]

VOLUME ["${APP_ROOT}/tmp"]
