FROM --platform=linux/x86_64 nginx:stable-alpine

RUN rm -f /etc/nginx/conf.d/*
COPY ./containers/nginx/nginx.prd.conf /etc/nginx/conf.d/

# デーモンをオフにして、フォアグラウンドで Nginx を実行させる
CMD /usr/sbin/nginx -g 'daemon off;' -c /etc/nginx/nginx.conf
