"""empty message

Revision ID: f6cb7fde0cb9
Revises: 0a9d4fbfa535
Create Date: 2024-03-23 09:14:20.217433

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f6cb7fde0cb9"
down_revision: Union[str, None] = "0a9d4fbfa535"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
